env:
  global:
    - CC_TEST_REPORTER_ID=c397b52ff4a5ea90a510bbc150700dcf0bb86d84b01698bdc1a3deb02dc0e5f3

language: ruby
rvm:
- 2.4.4
deploy:
  provider: heroku
  api_key:
    secure: Gp4G+Vt11Bd/yiNcpSQZTsuED/Qx1JEQ0gNt0cddcbJWOeJ3AfJWvdMII6+mRPT7TkKygbB1OdsGQiRCgfuwWkUDhbW44Aor2UP3SEGeQk7z572jBnYW+lbya3iy0+VZXsHs5c1qjw83aq3eXNPwlMF5tyjJAUh6aA4PGv/BAkVUMSCYCAq9+0PYuQMpHX83J1dCbEJAVfFU0iUEWSffe/TYri9HuncGwn6conwOPcMvPmFOws6pHbd1zA1mlyg9r9+Bhlh4ZSRRFqnN3uNhvxix29dwsid8R4q2waYzm5kT+ZGrRnSTnEms4i3x/f3DPSSdUgTB60qeUyxdtmhlM5DP2RjLnqWdpMs1gpG/N1RODCz0E8plMHi69fd/F/doJywhb9FRcWkFmXtEJNto24BhingF0ByCJXmYEi1P1iEtKpwreWcx862Emlk9/zT8KEOffYCE6efWSQEpDEJ4ou9KQTHvf4LUICFBKdyTY5zNspK8l5VAucTkNle1mLR8gUu2EjINiU2bcuuoGd6XA+keJIolGvbzTBdZpTjeWxKRjDPl34q5p9f/IEz0hAE3JTBmif+GeIW4gQ5EpQj01cXrYyIS2C6oxWrhcxUHY+IoJdc48dH0v/vhzkAjLxGwbgcspNXauklPDBj1vCd6UMSLlZSf9fcYDpY1KG1MvH0=
  app: pizzaprojectamine
  on:
    repo: aminebousselmi/PizzaProject
  run:
    - "rake db:migrate"
    - "rake cleanup"
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT